ALTER TABLE notification_batches
    ADD COLUMN IF NOT EXISTS pending   INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS delivered INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS failed    INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS cancelled INT NOT NULL DEFAULT 0;
